name: Create NPM Release

on:
  workflow_dispatch:

  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses:
          actions/checkout@v3
          # these if statements ensure that a publication only occurs when
          # a new release is created:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/'
      - name: Setup Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: NPM install
        run: npm ci
      - name: NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_CMS_API_URL: ${{ secrets.NEXT_PUBLIC_CMS_API_URL }}
