name: Create Pre-Release

on:
  workflow_dispatch:

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/'
      - name: Setup Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: NPM install
        run: npm ci
      - name: Create pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          npm version prerelease --preid=alpha
          git push --follow-tags
      - name: Publish to GitHub Package Registry
        run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_CMS_API_URL: ${{ secrets.NEXT_PUBLIC_CMS_STAGE_API_URL }}
