name: Trigger Renovate Bot

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: action-renovate-checkbox
        uses: Jolg42/action-renovate-checkbox@1.0.0
        with:
          master-issue-id: 9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
